### ISSUE TITLE
Save opend tabs on workspace switching

### ISSUE THREAD

**Issue by NickRimmer** [NickRimmer/insomnia-plugin-request-navigator#13]
Could be useful (=

**Comment by asyba** [comment]
yes plz do this, I have like 20 different workspace and constantly switching.

**Comment by asyba** [comment]
@NickRimmer I tried the new version but still is not working.
BTW: Im in the same "project" but switching to a different "collection"

**Comment by NickRimmer** [comment]
@asyba very strange. I've tested it for a few days. Switching between collections, in different working places - everything is perfectly fine. What version you can see in the plugins list?

**Comment by NickRimmer** [comment]
Could it be the same issue?
#18
