### ISSUE TITLE
Opened tabs are lost after Insomnia restarting

### ISSUE THREAD

**Issue by qiqingli** [NickRimmer/insomnia-plugin-request-navigator#17]
Insomnia 2023.4.0
Build date: 7/4/2023
OS: Darwin x64 22.5.0 （macOS 13.4.1）
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: x64

insomnia-plugin-request-navigator：0.1.13

Issue：After restarting insomnia, the opened tabs are lost, can this problem be solved

**Comment by NickRimmer** [comment]
Thank you, I will check it
