### ISSUE TITLE
New feature : add keyboard shortcut to close current tab

### ISSUE THREAD

**Issue by paulo-dc** [NickRimmer/insomnia-plugin-request-navigator#20]
Hi ! 
First of all many thanks for this plugin! Like it ! great add on for Insomnia.

I would like the possibility to add a keyboard shortcut (like `ctrl+w` or `ctrl+f4`) to close the current tab. Is it possible to add this to the plugin ?

Many thanks

**Comment by NickRimmer** [comment]
Hi @paulo-dc, nice idea. Let me check if we can set it from plugins perspective 👍

**Comment by NickRimmer** [comment]
Hey! Just a heads-up that I'm closing old tickets and archiving this repo. I've started working on my own client, where I'll be applying all the ideas I wanted to bring here 😊

It's called [RestApia](https://www.restapia.app/). Feel free to check it out!
