### ISSUE TITLE
Stop working with 2023.5 Insomnia version

### ISSUE THREAD

**Issue by NickRimmer** [NickRimmer/insomnia-plugin-request-navigator#21]
Tabs stop showing after update to a new version

**Comment by JdKock** [comment]
Same issue for me with Insomnia version 2023.5.5

**Comment by TorstenD-SAP** [comment]
Same issue for me in version 2023.5.5. The console reports the error:

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'props')`

at line 2771 in the file _...\Insomnia\plugins\insomnia-plugin-request-navigator\index.js_ (function `getReactRefs`)

**Comment by blackshot** [comment]
+1 on this

**Comment by NickRimmer** [comment]
I will look on this until end of this week, I cannot work without tabs in Insomnia anymore 😅

**Comment by tetsuhaut** [comment]
Don't know if it is the same problem, but trying to install the plugin gives me the following error:
```
Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"error","data":"Received invalid response from npm."}

    at a.invoke (node:electron/js2c/renderer_init:2:7723)
    at async onSubmit (file:///C:/Users/<edited>/AppData/Local/insomnia/app-2023.5.6/resources/app.asar/index-391c2d16.js:195:513)
```

**Comment by lmorganl** [comment]
still the issue on 2023.5.7

**Comment by NickRimmer** [comment]
Yeah... in Insomnia has no redux anymore plugin used for application state manipulation, I'm looking for another way to navigate.

**Comment by blackshot** [comment]
documentation says the are now using remix

**Comment by NickRimmer** [comment]
Yep, looks like I found a way to work with remix state from the plugin. Will push updates soon (;

**Comment by NickRimmer** [comment]
To update, you can install plugin again (not necessary to uninstall old version). Enter plugin name `insomnia-plugin-request-navigator` and click Install Plugin

![image](https://github.com/NickRimmer/insomnia-plugin-request-navigator/assets/1754265/54086198-fdbb-4438-beeb-b364b5718f2e)

**Comment by tetsuhaut** [comment]
Failed to install insomnia-plugin-request-navigator

There may be an issue with the plugin itself, as a note you can discover and install plugins from the [Plugin Hub.](https://insomnia.rest/plugins)
Additional Information
Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"warning","data":"package.json: No license field"}
{"type":"error","data":"Received invalid response from npm."}

    at a.invoke (node:electron/js2c/renderer_init:2:7723)
    at async onSubmit (file:///C:/Users/605500423/AppData/Local/insomnia/app-2023.5.7/resources/app.asar/index-7770d3c9.js:195:513)

**Comment by NickRimmer** [comment]
Hi, @tetsuhaut 
Wow, interesting. Thank you I will check it
