### ISSUE TITLE
Failed to install insomnia-plugin-request-navigator

### ISSUE THREAD

**Issue by NickRimmer** [NickRimmer/insomnia-plugin-request-navigator#24]
Failed to install insomnia-plugin-request-navigator

There may be an issue with the plugin itself, as a note you can discover and install plugins from the [Plugin Hub.](https://insomnia.rest/plugins)
Additional Information
Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"warning","data":"package.json: No license field"}
{"type":"error","data":"Received invalid response from npm."}

    at a.invoke (node:electron/js2c/renderer_init:2:7723)
    at async onSubmit (file:///C:/Users/605500423/AppData/Local/insomnia/app-2023.5.7/resources/app.asar/index-7770d3c9.js:195:513)

_Originally posted by @tetsuhaut in https://github.com/NickRimmer/insomnia-plugin-request-navigator/issues/21#issuecomment-1704743940_

**Comment by tetsuhaut** [comment]
Hi, any news ?

**Comment by tetsuhaut** [comment]
Is it maybe required to be logged in in insomnia to see the tabs?

**Comment by NickRimmer** [comment]
@tetsuhaut, nope, it should work without any registrations or logging in

**Comment by NickRimmer** [comment]
There is License information. So, the issue is with something different. Most probably `Received invalid response from npm.` means you cannot load NPM package information for some reason. It could be your local security settings (like custom root certificates). Unfortunately, I cannot reproduce it, I tried to remove/install the plugin - everything is working perfectly fine.

![image](https://github.com/NickRimmer/insomnia-plugin-request-navigator/assets/1754265/6b0499e3-ca8c-4824-908c-d41d39f46920)

Can you try to install any other plugins?

**Comment by tetsuhaut** [comment]
Thank you for the hint.
Indeed, trying to install another plugin fails too.
I am behind a corporate proxy, that is probably the reason why the install fails.
Do you know how I could display what Insomnia tries to have the `Received invalid response from npm.` response? Is there a verbose mode for example?<br>
I'll open an issue on the Insomnia side as well.

**Comment by tetsuhaut** [comment]
juste another question: do you know how I can install manually your plugin? I tried `npm install insomnia-plugin-request-navigator`, got the response 
```
npm info using npm@10.1.0
npm info using node@v20.7.0
npm verb title npm i insomnia-plugin-request-navigator
npm verb argv "i" "insomnia-plugin-request-navigator" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\605500423\AppData\Local\npm-cache\_logs\2023-09-27T15_11_08_256Z-
npm verb logfile C:\Users\605500423\AppData\Local\npm-cache\_logs\2023-09-27T15_11_08_256Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/insomnia-plugin-request-navigator 25ms (cache hit)
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 339ms

up to date, audited 19 packages in 876ms

found 0 vulnerabilities
npm verb exit 0
npm info ok
```
and found nothing in %PROFILE%\AppData\Roaming\Insomnia\plugins :(

**Comment by NickRimmer** [comment]
[insomnia-plugin-request-navigator.zip](https://github.com/NickRimmer/insomnia-plugin-request-navigator/files/12742415/insomnia-plugin-request-navigator.zip)

@tetsuhaut here is built version you can just copy to plugins folder. Folder path should be like this `C:\Users\USER\AppData\Roaming\Insomnia\plugins\insomnia-plugin-request-navigator`

**Comment by tetsuhaut** [comment]
unzipping the file you provided to %USERPROFILE%\AppData\Roaming\Insomnia\plugins\insomnia-plugin-request-navigator did the trick. Many thanks!

It would be great if you provided instructions on how to build your plugin (e.g. in https://github.com/NickRimmer/insomnia-plugin-request-navigator/blob/main/README.md), so that I am able to keep using it after potential updates.
Anyway, it works now!

**Comment by Saphyel** [comment]
I installed insomnia using snap and I can't install the plugin as well

**Comment by NickRimmer** [comment]
Hey! Just a heads-up that I'm closing old tickets and archiving this repo. I've started working on my own client, where I'll be applying all the ideas I wanted to bring here 😊

It's called [RestApia](https://www.restapia.app/). Feel free to check it out!
