### ISSUE TITLE
Tabs cross collections

### ISSUE THREAD

**Issue by Wuerike** [NickRimmer/insomnia-plugin-request-navigator#27]
Is it possible make it keep the tabs from one collection opened when switching to other?

**Comment by NickRimmer** [comment]
Hey! Just a heads-up that I'm closing old tickets and archiving this repo. I've started working on my own client, where I'll be applying all the ideas I wanted to bring here 😊

It's called [RestApia](https://www.restapia.app/). Feel free to check it out!
