### ISSUE TITLE
feature request: add tabs for grpc requests 

### ISSUE THREAD

**Issue by gAmUssA** [NickRimmer/insomnia-plugin-request-navigator#9]
Currently, tabs only work for REST requests.
Please add support of grpc requests in tabs.

![CleanShot 2023-07-13 at 16 46 28@2x](https://github.com/NickRimmer/insomnia-plugin-request-navigator/assets/433085/a496545e-18ef-4ddb-baa7-40c69c0d0fe4)

**Comment by NickRimmer** [comment]
You are right, it should be for grpc requests as well. Let me check it, thank you (;
